module.exports = Object.freeze({
    STUDENT_JOINED_LESSON: 'STUDENT_JOINED_LESSON',
    STUDENT_LEFT_LESSON: 'STUDENT_LEFT_LESSON',

    // student chose option/entered answer
    STUDENT_ENTERED_ANSWER: 'STUDENT_ENTERED_ANSWER',

    // start/end lesson
    ACTIVE_LESSON_STATUS_CHANGED: 'ACTIVE_LESSON_STATUS_CHANGED',

    // teacher shows right answer
    RIGHT_ANSWER_SHOWN: 'RIGHT_ANSWER_SHOWN',

    STUDENT_CHANGED_LESSON: 'STUDENT_CHANGED_LESSON',
    TEACHER_CHANGED_LESSON: 'TEACHER_CHANGED_LESSON',
});
