module.exports = Object.freeze({
    LESSON_STATUS_CHANGED: 'LESSON_STATUS_CHANGED',
    PRESENT_STUDENTS_CHANGED: 'PRESENT_STUDENTS_CHANGED',
    STUDENTS_ANSWERS_CHANGED: 'STUDENTS_ANSWERS_CHANGED',
    TEACHER_SHOWED_ANSWERS: 'TEACHER_SHOWED_ANSWERS',
    STUDENT_CURRENT_POSITION: 'STUDENT CURRENT POSITION',
    STUDENT_ON_LESSON: 'STUDENT ON LESSON',
});
